HLT_triggers:
  2022_preEE:
    BTagMu:
    - BTagMu_AK4DiJet110_Mu5
    - BTagMu_AK4DiJet170_Mu5
    - BTagMu_AK4DiJet20_Mu5
    - BTagMu_AK4DiJet40_Mu5
    - BTagMu_AK4DiJet70_Mu5
    - BTagMu_AK4Jet300_Mu5
  2022_postEE:
    BTagMu:
    - BTagMu_AK4DiJet110_Mu5
    - BTagMu_AK4DiJet170_Mu5
    - BTagMu_AK4DiJet20_Mu5
    - BTagMu_AK4DiJet40_Mu5
    - BTagMu_AK4DiJet70_Mu5
    - BTagMu_AK4Jet300_Mu5
  2023_preBPix:
    BTagMu:
    - BTagMu_AK4DiJet110_Mu5
    - BTagMu_AK4DiJet170_Mu5
    - BTagMu_AK4DiJet20_Mu5
    - BTagMu_AK4DiJet40_Mu5
    - BTagMu_AK4DiJet70_Mu5
    - BTagMu_AK4Jet300_Mu5
  2023_postBPix:
    BTagMu:
    - BTagMu_AK4DiJet110_Mu5
    - BTagMu_AK4DiJet170_Mu5
    - BTagMu_AK4DiJet20_Mu5
    - BTagMu_AK4DiJet40_Mu5
    - BTagMu_AK4DiJet70_Mu5
    - BTagMu_AK4Jet300_Mu5
